### ISSUE TITLE
Tracking: Support the full JSON Path language

### ISSUE THREAD

**Issue by b41sh** [databendlabs/jsonb#12]
`JSON path` has already implemented the basic elements accessors and comparison predicates filter expression, in order to support the full `JSON Path` language, the following tasks need to be done further.

- Variables:
    - [ ] Variables
- Modes:
    - [ ] `lax`
    - [ ] `strict`
- Item methods:
    - [ ] `type()`
    - [ ] `size()`
    - [ ] `double()`
    - [ ] `ceiling()`
    - [ ] `floor()`
    - [ ] `abs()`
    - [ ] `datetime()`
    - [ ] `keyvalue()`
- Arithmetic expressions
    - [x] Unary `+` or `-`
    - [x] Binary `+`, `-`, `*`, `/`, `%`
- Filter expression
    - [x] `exists` path predicate
    - [ ] `like_regex` predicate
    - [x] `starts with` predicate
    - [ ] `is unknown` predicate

The syntax and functionality of `JSON Path` should be implemented in accordance with the `SQL:2016 (ISO/IEC 9075:2016)` standard. Here are some references: 

- [SQL Technical Reports — Part 6: SQL support for JavaScript Object Notation (JSON)](http://www.sai.msu.su/~megera/postgres/files/c067367_ISO_IEC_TR_19075-6_2017.pdf)
- [PostgreSQL Jsonpath in examples and roadmap](https://www.postgresql.eu/events/pgconfeu2019/sessions/session/2555/slides/221/jsonpath-pgconfeu-2019.pdf)
- [Gentle Guide to JSONPATH in PostgreSQL](https://github.com/obartunov/sqljsondoc/blob/master/jsonpath.md)
